force-app/main/default/objects/Gatherica_Event__c/Gatherica_Event__c.object-meta.xml
<CustomObject>
    <label>Gatherica Event</label>
    <nameField>
        <label>Gatherica Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gatherica Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gatherica_Event__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Category__c.field-meta.xml
<CustomField>
    <fullName>Event_Category__c</fullName>
    <label>Event Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Education &amp; Learning</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Business &amp; Professional</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Social &amp; Community</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Innovation</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids</fullName>
            </value>
            <value>
                <fullName>Travel &amp; Adventure</fullName>
            </value>
            <value>
                <fullName>Lifestyle &amp; Fashion</fullName>
            </value>
            <value>
                <fullName>Music &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Science &amp; Nature</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <label>Event Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Publisher__c.field-meta.xml
<CustomField>
    <fullName>Event_Publisher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Publisher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gatherica Events</relationshipLabel>
    <relationshipName>Gatherica_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled - SPAM</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>About To Start</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GathericaHomeServiceHandler.cls
/**
* @File Name : GathericaHomeServiceHandler.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : September 6, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 6, 2024 |   | Initial Version
**/

public class GathericaHomeServiceHandler {

	Public static List<EventWrapper> getEventList(Integer recordCount, String username) {
		List<EventWrapper> eventWrapperList = new List<EventWrapper>();
		Set<String> subscribedEventList = new Set<String> ();
		List<Gatherica_Event__c> gathericaEventList = GathericaHomeSelector.getEventList(recordCount);
		if(String.isNotBlank(username)) {
			// get all subscribed events by this username
			subscribedEventList = GathericaHomeSelector.getSubscribedEventList(username);
		}
		for(Gatherica_Event__c eventRecord : gathericaEventList) {
			eventWrapperList.add (
				new EventWrapper (
					String.valueOf(eventRecord.Id),
					eventRecord.name,
					eventRecord.Description__c,
					String.valueOf(eventRecord.Event_Date__c),
					eventRecord.Event_Publisher__r.Name,
					eventRecord.Event_Category__c,
					100,
					subscribedEventList.contains(eventRecord.Id),
					eventRecord.Event_Status__c
				)
			);
		}
		return eventWrapperList;
	}
}