force-app/main/default/objects/Contact/fields/contact_user_name__c.field-meta.xml
<CustomField>
    <fullName>contact_user_name__c</fullName>
    <label>contact user name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/Gatherica_Event__c.object-meta.xml
<CustomObject>
    <label>Gatherica Event</label>
    <nameField>
        <label>Gatherica Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gatherica Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gatherica_Event__c/fields/completed__c.field-meta.xml
<CustomField>
    <fullName>completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/contact_Email__c.field-meta.xml
<CustomField>
    <fullName>contact_Email__c</fullName>
    <label>contact Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Category__c.field-meta.xml
<CustomField>
    <fullName>Event_Category__c</fullName>
    <label>Event Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Education &amp; Learning</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Arts &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Business &amp; Professional</fullName>
            </value>
            <value>
                <fullName>Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Social &amp; Community</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Innovation</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Sports &amp; Recreation</fullName>
            </value>
            <value>
                <fullName>Family &amp; Kids</fullName>
            </value>
            <value>
                <fullName>Travel &amp; Adventure</fullName>
            </value>
            <value>
                <fullName>Lifestyle &amp; Fashion</fullName>
            </value>
            <value>
                <fullName>Music &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Science &amp; Nature</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <label>Event Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Publisher__c.field-meta.xml
<CustomField>
    <fullName>Event_Publisher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Publisher</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gatherica Events</relationshipLabel>
    <relationshipName>Gatherica_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled - SPAM</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>About To Start</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gatherica_Event__c/fields/External_Website_URL__c.field-meta.xml
<CustomField>
    <fullName>External_Website_URL__c</fullName>
    <label>External Website URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/gatherica_event_Users__c/gatherica_event_Users__c.object-meta.xml
<CustomObject>
    <label>gatherica event Users</label>
    <nameField>
        <displayFormat>GE USER - {00000}</displayFormat>
        <label>gatherica event Users Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>gatherica event Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/gatherica_event_Users__c/fields/Gatherica_Event__c.field-meta.xml
<CustomField>
    <fullName>Gatherica_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gatherica Event</label>
    <referenceTo>Gatherica_Event__c</referenceTo>
    <relationshipLabel>gatherica event Users</relationshipLabel>
    <relationshipName>gatherica_event_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/gatherica_event_Users__c/fields/gatherica_User__c.field-meta.xml
<CustomField>
    <fullName>gatherica_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>gatherica User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>gatherica event Users</relationshipLabel>
    <relationshipName>gatherica_event_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GathericaHomeSelector.cls
/**
* @File Name : GathericaHomeSelector.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : September 6, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 6, 2024 |   | Initial Version
**/

public class GathericaHomeSelector {

	public static Set<String> getSubscribedEventList(String username) {
		Set<String> subscribedEventList = new Set<String>();
		for(gatherica_event_Users__c user : [Select Gatherica_Event__r.Id from gatherica_event_Users__c where gatherica_User__r.contact_user_name__c =: username]) {
			subscribedEventList.add(user.Gatherica_Event__r.Id);
		}
		return subscribedEventList;
	}

	Public static List<Gatherica_Event__c> getEventList(Integer recordCountLimit){
		return [
				SELECT Id, Completed__c, Contact_Email__c, Name,
				Description__c, Event_Category__c, Event_Date__c, 
				Event_Publisher__r.Name, Event_Status__c, External_Website_URL__c, 
				Price__c FROM Gatherica_Event__c WHERE Event_Date__c != NULL LIMIT :recordCountLimit
			];
	}
}